### ISSUE TITLE
Support for AWS profile parameter

### ISSUE THREAD

**Issue by tdalbo92** [miroapp/cloud-data-import#138]
## Feature Description

I cannot use the aws cli standalone - it's configured on my system to reference IAM Identity Center profiles via SSO.  Support for passing this into the underlying calls would allow us to use this tool.  Something like `--profile` or `-p` and then the value being the reference to the aws cli configured profile.

## Use Case

Users who are using SSO with profiles need this feature to use this tool.

## Suggested Solution

The profile can be a straight passthrough to all aws cli commands under the hood.  All aws cli commands support it.  It could be appended to the end in every case.

## Alternatives Considered

None considered

## Additional Context

Without profile support, the error is similar to being unauthenticated:

`InvalidClientTokenId: The security token included in the request is invalid`

## Checklist

- [x] I have searched for similar feature requests.
- [x] I have included all necessary information.

**Comment by tdalbo92** [comment]
A workaround is to set the `AWS_PROFILE` env var, but this may not be the most desirable thing for some users.

**Comment by alireza-sheikholmolouki** [comment]
Hey @tdalbo92! Thanks for opening this issue!

Your workaround is definitely standard, but we'll consider your suggestion as well. We think it's a great idea!

If you'd like to see it implemented sooner, feel free to open a PR. We'd be happy to have your contribution on this project if you're interested:)

**Comment by andries-miro** [comment]
Hi @tdalbo92!

Hope all is well. We've added support for the profile parameter in the latest version.

Does this satisfy your technical needs? Definitely let us know if you run into any issues.
