### ISSUE TITLE
Not able to import the JSON-file in Miro

### ISSUE THREAD

**Issue by jan-arve-nygard-adsk** [miroapp/cloud-data-import#302]
> ❗ Important Note: You may have encountered a permissions error that is solvable by your Cloud Provider administrator. You should have get the relevant logs if it's a permission error.

## Description

This bug might be in the Miro service and not the `cloud-data-import` tool, but the JSON export from the tool is not accepted by the import feature.

Error message: `The JSON file is outdated. Please run the script and generate a new one`

Head of output file:

```
{
  "provider": "aws",
  "docVersion": "0.1.1",
  "resources": {},
  "tags": {},
  "processed": {
    "resources": {
```

## Commands and Options

`npx @mirohq/cloud-data-import@latest --regions all -p profile -o data.json`

## Expected Behavior

Be able to import the file into Miro

## Actual Behavior

Got the error message: `The JSON file is outdates. Please run the script and generate a new one`

## Logs (or Screenshots)

![Pasted Graphic](https://github.com/user-attachments/assets/e9f78604-b583-4ad4-9e50-891f27e50448)

## Environment

- **OS**: macOS
- **Terminal**: zsh (oh-my-zsh)
- **Script Version**: v0.12.3

**Comment by jan-arve-nygard-adsk** [comment]
That worked like a charm @alireza-sheikholmolouki. I actually just tried to bump to a newer version, and not an older version before filing the issue.

Thanks!

**Comment by alireza-sheikholmolouki** [comment]
Hi @jan-arve-nygard-adsk, thanks to your report, the bug is fixed! You should now be able to view your previous and new JSON files with the correct version.

Thank you for your help, and keep that bug report spirit alive! We really appreciate it! 🙌
